spring.application.name=SarichiCrocheting
server.port=8080
server.servlet.context-path=/api
spring.data.mongodb.uri=mongodb+srv://Sara:Sara123@empresarialessara.vmeolxj.mongodb.net/sarichi_crocheting?retryWrites=true&w=majority
spring.data.mongodb.database=sarichi_crocheting
spring.data.mongodb.auto-index-creation=true
# JWT Configuration
app.jwt.secret=sarichi_crocheting_2026_super_secret_key_for_jwt_tokens_must_be_long_enough_64chars
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rivera.saravalentina@gmail.com
spring.mail.password=uxmo oygx doso dkdt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.root=INFO
logging.level.com.sarichi.crocheting=DEBUG
management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
app.frontend.url=http://localhost:8080/api